const BUTTON_WIDTH = 60;
const BUTTON_SPACING = 20;
const VERTICAL_SPACING = 10;
const FINAL_HEIGHT = 60;

const CARD_WIDTH = 350;
const CARD_HEIGHT = 180;

export const SIZES = {
  INITIAL_TITLE_FONT_SIZE: 15,
  FINAL_TITLE_FONT_SIZE: 10,
  CARD_HEIGHT,
  CARD_WIDTH,
  SPACING: 5,
  BUTTON_WIDTH,
  BUTTON_SPACING,
  VERTICAL_SPACING,
  FINAL_HEIGHT,
  TOTAL_BUTTON_WIDTH: BUTTON_WIDTH + BUTTON_SPACING,
  TOTAL_CARD_HEIGHT: CARD_HEIGHT + VERTICAL_SPACING,
  TOTAL_FINAL_CARD_HEIGHT: FINAL_HEIGHT + VERTICAL_SPACING,
  HORIZONTAL_SCROLL_START_BREAKPOINT: CARD_WIDTH * 0.2,
};
